export const DEFAULT_EMAIL_MAX_LENGTH = 50;
export const DEFAULT_FULL_NAME_MAX_LENGTH = 35;
export const DEFAULT_PASSWORD_MIN_LENGTH = 8;
export const DEFAULT_PASSWORD_MAX_LENGTH = 50;
export const DEFAULT_DESCRIPTION_MAX_LENGTH = 255;
